#!/bin/sh
# cupsconfig - Start and configure cups
# (C) Klaus Knopper Jun 2001
# (C) 2004-2008 Stefan Lippers-Hollmann <s.l-h@gmx.de>

PATH="/bin:/sbin:/usr/bin:/usr/sbin"
export PATH

if [ "$(id -u)" -ne 0 ]; then
	[ -x "$(which su-to-root)" ] && exec su-to-root -X -c "$0" "$@"
	printf "ERROR: $0 needs root capabilities, please start it as root\n\n" >&2
	exit 1
fi

HPLIP="$(pidof hpiod)"
if [ -z "$HPLIP" ]; then
	[ -x /etc/init.d/hplip ] && /etc/init.d/hplip start
fi

CUPSPID="$(pidof cupsd)"
if [ -z "$CUPSPID" ]; then
	[ -x /etc/init.d/cupsys ] && /etc/init.d/cupsys start
	sleep 4
fi

for i in $(seq 1 20); do
	sleep 2

	if lpstat -r; then
		if [ -x /usr/bin/gnome-cups-manager ] ; then
			update-rc.d -f cupsys defaults
			[ -n "$DISPLAY" ] && exec /usr/bin/gnome-cups-manager
		elif [ -x /usr/bin/kcmshell ] ; then
			if kcmshell --nocrashhandler printers; then
				update-rc.d -f cupsys defaults
			else
				kcmshell --nocrashhandler printers
			fi
		else
			update-rc.d -f cupsys defaults
			[ -n "$DISPLAY" ] && exec x-www-browser "http://127.0.0.1:631"
			[ -z "$DISPLAY" ] && exec   www-browser "http://127.0.0.1:631"
		fi 
		break
	else
		case "$LANG" in
			es*)
				[ -n "$DISPLAY" ] && [ -x /usr/bin/xmessage ] && exec xmessage 'Â¡No puedo arrancar el servidor CUPS!'
				echo 'Â¡No puedo arrancar el servidor CUPS!' 1>&2
				exit 2
				;;
			*)
				[ -n "$DISPLAY" ] && [ -x /usr/bin/xmessage ] && exec xmessage 'Cannot start CUPS server!'
				echo 'Cannot start CUPS server!' 1>&2
				exit 2
				;;
		esac
	fi
done

