#!/bin/sh
# cupsconfig - Start and configure cups
# (C) Klaus Knopper Jun 2001
# (C) 2004-2007 Stefan Lippers-Hollmann <s.l-h@gmx.de>

PATH="/bin:/sbin:/usr/bin:/usr/sbin"
export PATH

HPLIP="$(pidof hpiod)"
if [ -z "$HPLIP" ]; then
	[ -x /etc/init.d/hplip ] && su-me /etc/init.d/hplip start
fi

CUPSPID="$(pidof cupsd)"
if [ -z "$CUPSPID" ]; then
	[ -x /etc/init.d/cupsys ] && su-me /etc/init.d/cupsys start
	sleep 4
fi

for i in $(seq 1 20); do
	sleep 2
	
	if lpstat -r; then
		if [ -x /usr/bin/kcmshell ]; then
			if su-me kcmshell --nocrashhandler printers; then
				su-me update-rc.d -f cupsys defaults
			else
				kcmshell --nocrashhandler printers
			fi
		else
			su-me update-rc.d -f cupsys defaults
			[ -z "$DISPLAY" ] && exec x-www-browser "http://127.0.0.1:631"
			[ -n "$DISPLAY" ] && exec   www-browser "http://127.0.0.1:631"
		fi

		break
	else
		case "$LANG" in
			es*)
				[ -z "$DISPLAY" ] && [ -x /usr/bin/xmessage ] && exec xmessage '¡No puedo arrancar el servidor CUPS!'
				echo '¡No puedo arrancar el servidor CUPS!' 1>&2
				exit 1
				;;
			*)
				[ -z "$DISPLAY" ] && [ -x /usr/bin/xmessage ] && exec xmessage 'Cannot start CUPS server!'
				echo 'Cannot start CUPS server!' 1>&2
				exit 1
				;;
		esac
	fi
done

