#!/bin/sh
# cupsconfig - Start and configure cups
# (C) Klaus Knopper Jun 2001
# (C) 2004-2006 Stefan Lippers-Hollmann <s.l-h@gmx.de>

PATH="/bin:/sbin:/usr/bin:/usr/sbin"
export PATH

HPLIP="$(pidof hpiod)"
if [ -z "$HPLIP" ]; then
	[ -x /etc/init.d/hplip ] && kanotix-su /etc/init.d/hplip start
fi

CUPSPID="$(pidof cupsd)"
if [ -z "$CUPSPID" ]; then
	[ -x /etc/init.d/cupsys ] && kanotix-su /etc/init.d/cupsys start
	sleep 4
fi

for i in $(seq 1 20); do
	sleep 2
	lpstat -r >/dev/null 2>&1
	error="$?"
	if [ "$?" -eq 0 ]; then
		if kanotix-su kcmshell --nocrashhandler printers; then
			kanotix-su update-rc.d -f cupsys defaults
		else
			kcmshell --nocrashhandler printers
		fi

		break
	else
		case "$LANG" in
			es*)
				exec xmessage '¡No puedo arrancar el servidor CUPS!'
				;;
			*)
				exec xmessage 'Cannot start CUPS server!'
				;;
		esac
	fi
done

